### ISSUE TITLE
Error: ResourceLimitExceeded

### ISSUE THREAD

**Issue by beckman71** [awslabs/aws-step-functions-ebs-snapshot-mgmt#3]
Hi,

I thought this is a wonderful approach for disaster recovery aspects. 
I have implemented this solution to create daily snapshots from our volumes and to copy them across to a different region.  (eu-west-1 to eu-central-1) 

But if there are a couple of snapshots you run into errors.

While investigating my CloudWatch Logs I found the cause to be:

[ResourceLimitExceeded: Too many snapshot copies in progress. The limit is 5 for this destination region.]
message: 'Too many snapshot copies in progress. The limit is 5 for this destination region.',

Not sure how to resolve this properly. I have asked the support to increase the limit, but a programmatic approach would be best. I think of a SQS to rather queue jobs with lambda as a consumer to copy then snapshots rather sequentially.

Any ideas?

Many thanks

Ralph

**Comment by thedoc31** [comment]
I thought about implementing SQS for this as well, but the easiest solution was to have AWS increase our limit of snapshot copies in progress. After speaking with our TAM and an engineer from the EBS team, I was satisfied that there was plenty of bandwidth to handle it. We are performing more than 30 snapshots at once now without issue.

**Comment by beckman71** [comment]
Thank you Casalino for your feedback, 

I almost forgot this one. I actually did the same and have requested to increase the limits to 20 once without problems, but still have some failing sometimes.  Still I can live with it as is until there is a new backup service from AWS I rather would use. 

Thanks again

Ralph
